import type { Metadata } from "next";
import LegalPage, { type LegalSection } from "@/components/legal/LegalPage";

export const metadata: Metadata = {
  title: "Terms and Conditions",
  description: "Terms governing use of the Manisha Belvalkar website, services, courses, and products.",
  alternates: { canonical: "/terms-and-conditions" },
};

const sections: LegalSection[] = [
  { title: "Acceptance of these terms", paragraphs: ["By using this website, creating an account, submitting a booking, purchasing a product or course, or using an offering, you agree to these terms and the policies linked from them. If you do not agree, please do not continue with the relevant feature or purchase."] },
  { title: "Eligibility and accounts", items: ["You must be legally capable of entering into a contract. A parent or lawful guardian must act for a minor.", "Provide accurate, current information and keep your sign-in credentials confidential.", "You are responsible for activity under your account. Notify us promptly if you suspect unauthorised access.", "We may restrict an account or request where needed for security, suspected misuse, abusive conduct, non-payment, or violation of these terms."] },
  { title: "Services and bookings", items: ["A website request is not a confirmed appointment until availability, price, payment, format, and timing are confirmed by Manisha Belvalkar or her authorised team.", "Arrive or join on time and provide a safe, suitable environment for online sessions.", "Advice and practices are personal guidance and educational support; outcomes differ between individuals and are not guaranteed.", "Rescheduling, cancellation, and refunds are governed by the Refund and Cancellation Policy."] },
  { title: "Products and courses", items: ["Descriptions, photographs, prices, inclusions, and availability are presented as accurately as reasonably possible. Minor colour or packaging differences may occur.", "Course access is personal and may not be shared, copied, recorded, resold, or redistributed unless written permission is given.", "Product delivery, damage, and return matters are governed by the Shipping and Delivery Policy and Refund and Cancellation Policy."] },
  { title: "Prices and payments", paragraphs: ["Prices are shown in Indian Rupees unless stated otherwise. Any taxes, delivery charges, payment instructions, or confirmed adjustments will be disclosed before completion. Fixed-price offerings may use Razorpay secure checkout. Consultation-priced offerings may first be recorded as a request and continued on WhatsApp. A charge is complete only after the payment provider and our records confirm it."], items: ["Do not send payment to an account or link that has not been confirmed through the official contact details on this website.", "An order may be cancelled and refunded if a pricing, availability, or catalogue error makes fulfilment impossible."] },
  { title: "Intellectual property", paragraphs: ["Website text, course material, videos, artwork, oracle content, branding, photographs, exercises, and downloadable material are owned by or licensed to Manisha Belvalkar. You receive only a limited, personal, non-transferable right to use purchased material for its intended purpose."], items: ["Do not reproduce, publish, sell, distribute, scrape, modify, or create commercial derivatives without written permission.", "Do not record private sessions or live workshops without the express consent of everyone involved."] },
  { title: "Acceptable use", items: ["Do not attempt to gain unauthorised access, introduce harmful code, impersonate another person, or disrupt the website.", "Do not use the website or services for unlawful, threatening, abusive, fraudulent, or discriminatory activity.", "Do not submit content that violates another person's privacy or intellectual-property rights."] },
  { title: "Disclaimers and responsibility", paragraphs: ["Spiritual, Tarot, mentoring, wellbeing, energy, astrology, numerology, Vastu, and related offerings do not replace qualified medical, mental-health, legal, or financial advice. You remain responsible for your decisions and actions. Please read the full Disclaimer before booking."], items: ["Nothing on this website promises a specific result, diagnosis, prediction, cure, income, relationship outcome, or other guaranteed result.", "If you face a medical or mental-health emergency, contact an appropriate licensed professional or emergency service immediately."] },
  { title: "Availability and liability", paragraphs: ["We work to keep information and services available, but interruptions, third-party failures, delays, errors, or events outside reasonable control may occur. To the extent allowed by applicable law, liability will be limited to direct loss arising from the relevant transaction and will not exceed the amount paid for that transaction. Nothing in these terms excludes a consumer right or liability that cannot lawfully be excluded."] },
  { title: "Changes, law, and contact", paragraphs: ["We may update these terms when services, technology, or legal requirements change. The date above shows the latest version. These terms are governed by the laws of India, and disputes are subject to the courts or forums having jurisdiction under applicable law. Questions may be sent to manishabelvalkar@gmail.com."] },
];

export default function TermsPage() {
  return <LegalPage eyebrow="Website terms" title="Terms and conditions" introduction="These terms set clear expectations for using this website and for requesting services, courses, sessions, and products." sections={sections} />;
}
